project:
  type: default
  output-dir: _rendered

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    code-link: true
    df-print: paged
    embed-resources: true
    output-file: "{{ slug }}"

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
