project:
  type: default
  output-dir: _rendered

format:
  revealjs:
    theme: [default]
    slide-number: true
    transition: slide
    background-transition: fade
    code-fold: false
    code-tools: true
    code-link: true
    embed-resources: true
    output-file: "{{ slug }}"

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
