project:
  type: default

# Single presentation project - revealjs slides by default

format:
  revealjs:
    theme: [default]
    slide-number: true
    transition: slide
    background-transition: fade
    code-fold: false
    code-tools: true
    code-link: true
    embed-resources: true

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
