project:
  type: default

execute:
  echo: true
  warning: true
  message: false
  error: false
  cache: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    df-print: paged
    fig-width: 8
    fig-height: 6
    embed-resources: true